import os
import hmac
import hashlib
import logging
from typing import Optional, Dict, Any
import razorpay
from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger("payguard.payment_service")


class PaymentServiceError(Exception):
    """Base exception for payment service operations."""
    pass


class PaymentService:
    """Service handling integration with Razorpay Test Mode."""

    def __init__(
        self,
        key_id: Optional[str] = None,
        key_secret: Optional[str] = None,
    ):
        self.key_id = key_id or os.getenv("RAZORPAY_KEY_ID", "")
        self.key_secret = key_secret or os.getenv("RAZORPAY_KEY_SECRET", "")
        self._client: Optional[razorpay.Client] = None

    @property
    def client(self) -> razorpay.Client:
        """Lazily initializes and returns the Razorpay client."""
        if self._client is None or self._client.auth != (self.key_id, self.key_secret):
            if not self.key_id or not self.key_secret:
                logger.warning("RAZORPAY_KEY_ID or RAZORPAY_KEY_SECRET not set in environment.")
            self._client = razorpay.Client(auth=(self.key_id, self.key_secret))
        return self._client

    def get_public_key(self) -> str:
        """Returns the public Razorpay Key ID safe for client-side consumption."""
        return self.key_id

    def create_order(
        self,
        amount: float,
        currency: str = "INR",
        receipt: Optional[str] = None,
        notes: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """Creates a Razorpay order in Test Mode using the validated final amount.

        Args:
            amount: Final amount in INR (will be converted to paise).
            currency: 3-letter currency code (default 'INR').
            receipt: Internal transaction/order reference.
            notes: Metadata dictionary.

        Returns:
            Dict containing order details returned by Razorpay API.
        """
        # Razorpay expects amount in smallest currency unit (paise for INR)
        amount_in_paise = int(round(amount * 100))
        if amount_in_paise <= 0:
            raise PaymentServiceError(f"Invalid transaction amount: {amount}")

        order_data = {
            "amount": amount_in_paise,
            "currency": currency.upper(),
            "payment_capture": 1,  # Auto capture payment upon authorization
        }
        if receipt:
            order_data["receipt"] = str(receipt)[:40]
        if notes:
            order_data["notes"] = {str(k): str(v)[:50] for k, v in notes.items()}

        try:
            logger.info(f"Creating Razorpay Test order: amount=INR {amount:.2f} ({amount_in_paise} paise), receipt={receipt}")
            order = self.client.order.create(data=order_data)
            logger.info(f"Razorpay order created successfully: ID={order.get('id')}")
            return order
        except Exception as e:
            logger.error(f"Failed to create Razorpay order: {e}")
            raise PaymentServiceError(f"Razorpay order creation failed: {str(e)}")

    def verify_payment_signature(
        self,
        razorpay_order_id: str,
        razorpay_payment_id: str,
        razorpay_signature: str,
    ) -> bool:
        """Verifies the authenticity of a Razorpay payment signature using HMAC SHA256.

        Args:
            razorpay_order_id: Order ID generated by Razorpay.
            razorpay_payment_id: Payment ID received upon transaction completion.
            razorpay_signature: Cryptographic signature provided by Razorpay.

        Returns:
            bool: True if signature is valid, False otherwise.
        """
        if not razorpay_order_id or not razorpay_payment_id or not razorpay_signature:
            logger.warning("Missing required parameters for signature verification.")
            return False

        if not self.key_secret:
            logger.error("Cannot verify signature: RAZORPAY_KEY_SECRET is missing.")
            return False

        try:
            # First try official SDK utility verification
            params_dict = {
                "razorpay_order_id": razorpay_order_id,
                "razorpay_payment_id": razorpay_payment_id,
                "razorpay_signature": razorpay_signature,
            }
            self.client.utility.verify_payment_signature(params_dict)
            logger.info(f"Signature verified successfully for Order={razorpay_order_id}, Payment={razorpay_payment_id}")
            return True
        except razorpay.errors.SignatureVerificationError:
            logger.warning(f"Signature verification failed for Order={razorpay_order_id}, Payment={razorpay_payment_id}")
            return False
        except Exception as e:
            logger.warning(f"SDK verification exception ({e}), falling back to direct HMAC-SHA256...")
            # Fallback deterministic HMAC-SHA256 check
            msg = f"{razorpay_order_id}|{razorpay_payment_id}".encode("utf-8")
            generated_signature = hmac.new(
                self.key_secret.encode("utf-8"),
                msg,
                hashlib.sha256,
            ).hexdigest()
            is_valid = hmac.compare_digest(generated_signature, razorpay_signature)
            logger.info(f"Direct HMAC comparison result: {is_valid}")
            return is_valid


payment_service = PaymentService()
